name: BlockCommands
version: '${project.version}'
main: me.luucka.blockcommands.BlockCommandsPlugin
api-version: '1.20'
authors: [ LuuckA ]
description: Block commands
commands:
  blockcommands:
    description: Reload plugin
    permission: blockcommands.admin
libraries:
  - org.spongepowered:configurate-yaml:${libs.configurate-yaml}
